/* eslint-disable @typescript-eslint/no-require-imports */
const fs=require('node:fs');
const assert=require('node:assert/strict');
const data=require('../.test-build/src/data/kelarune.js');
const engine=require('../.test-build/src/engine/scenarioEngine.js');
const {forecastSku,revenueWindow}=require('../.test-build/src/engine/forecastEngine.js');
const {inventoryFor}=require('../.test-build/src/engine/inventoryEngine.js');
const {recommend}=require('../.test-build/src/engine/recommendationEngine.js');
const {generateHistory}=require('../.test-build/src/data/dataset.js');
const base=engine.buildPlan(engine.defaultState());
const round=n=>Number(n.toFixed(6));
const output={source:'Fresh calls to compiled current source, with temporary in-memory counterfactuals; no application files changed.',tests:[],canonical:[],scenarios:[],evidence:{}};
function check(name,fn){try{fn();output.tests.push({name,status:'pass'});}catch(e){output.tests.push({name,status:'fail',message:e.message});}}
function near(a,b){assert.ok(Math.abs(a-b)<1e-6,`${a} !== ${b}`);}
for(const id of ['mango-12','berry-6','citrus-12','lime-6','starter-kit']){const s=data.getSku(id);const inv=inventoryFor(s,forecastSku(s,13,data.events),data.purchaseOrders,s.leadTimeWeeks,engine.defaultState(id).incomingInventory,0,0,data.events.some(e=>e.type==='bfcm'&&e.confirmed&&e.skuIds.includes(id)));output.canonical.push({id,onHand:s.currentInventory,demand:inv.weeklyDemand,cover:inv.weeksOfCover,roundedCover:inv.weeksOfCover.toFixed(1),lead:s.leadTimeWeeks,incoming:inv.incomingInventory,risk:inv.risk});}
check('Canonical five SKU covers and statuses',()=>{['3.4','13.1','5.2','5.2','6.0'].forEach((n,i)=>assert.equal(output.canonical[i].roundedCover,n));assert.deepEqual(output.canonical.map(r=>r.risk),['High risk','Overstock','Watch','Healthy','Healthy']);});
check('Executive base reconciliation',()=>{near(base.revenue30,318000);near(base.revenueGrowthPct,8.4);near(base.riskValue,42000);assert.equal(base.attention,5);assert.equal(base.stockouts,3);assert.equal(base.confidence,'Moderate');});
output.evidence.executive={revenue30:base.revenue30,previous30:base.previous30,growth:base.revenueGrowthPct,riskValue:base.riskValue,high:base.high,watch:base.watch,attention:base.attention,stockouts:base.stockouts,confidence:base.confidence};
for(const [name,changes] of [['base',{}],['Mango +20%',{demandUpliftPct:20}],['Mango +50%',{demandUpliftPct:50}],['portfolio upside',{scenarioMode:'upside'}],['portfolio downside',{scenarioMode:'downside'}],['Mango purchase 5000',{purchaseQuantity:5000}],['Mango promotion 20%',{promotionEnabled:true,promotionDiscountPct:20}]]){
 const p=engine.buildPlan({...engine.defaultState(),...changes});output.scenarios.push({name,revenue30:round(p.revenue30),growth:round(p.revenueGrowthPct),weeklyDemand:p.selected.inventory.weeklyDemand,cover:round(p.selected.inventory.weeksOfCover),stockout:p.selected.inventory.stockoutDate,breach:p.selected.inventory.breach,required:p.selected.inventory.requiredInventory,gap:p.selected.inventory.reorderGap,capital:p.workingCapital,high:p.high,watch:p.watch,stockouts:p.stockouts,previousRevenueWeek1:p.revenueSeries[0].previous,recommendation:p.selected.recommendations[0].recommendation,stockoutDaysEarlier:engine.comparePlans(p,base).stockoutDaysEarlier});
}
check('Scenario +20% propagates coherent units, revenue, cover and chart dates',()=>{const p=engine.buildPlan({...engine.defaultState(),demandUpliftPct:20});near(p.selected.inventory.weeklyDemand,846);near(p.revenue30-base.revenue30,705*.2*24*.98*30/7);near(p.selected.inventory.weeksOfCover,2400/846);assert.equal(p.selected.inventory.stockoutDate,p.selected.inventory.projection.find(x=>x.projected<=0).weekStart);assert.notEqual(p.selected.recommendations[0].recommendation,base.selected.recommendations[0].recommendation);});
check('Thirty-day chart sum equals thirty-day total',()=>near(revenueWindow(base.revenueSeries,30).reduce((n,p)=>n+p.revenue,0),base.revenue30));
check('Inventory available snapshot feeds cover',()=>{const snap=data.snapshots.find(s=>s.skuId==='mango-12');const original={...snap};try{snap.available=1200;snap.committed=1200;const p=engine.buildPlan(engine.defaultState());output.evidence.available={snapshotAvailable:snap.available,computedCover:p.selected.inventory.weeksOfCover,expectedCover:1200/705};near(p.selected.inventory.weeksOfCover,1200/705);}finally{Object.assign(snap,original);}});
check('Cover uses available, independently of optional shrink',()=>{const s=data.getSku('mango-12');const inv=inventoryFor(s,forecastSku(s,13,data.events),data.purchaseOrders,5,1200,0,.1);output.evidence.shrink={cover:inv.weeksOfCover,expectedCover:data.snapshots[0].available/705,usable:inv.usableInventory,firstProjection:inv.projection[0].projected,literalCurrentProjection:2400-705};near(inv.weeksOfCover,data.snapshots[0].available/705);});
check('Previous revenue forecast is immutable under a new promotion assumption',()=>{const p=engine.buildPlan({...engine.defaultState(),promotionEnabled:true,promotionDiscountPct:20});output.evidence.previous={before:base.revenueSeries[0].previous,after:p.revenueSeries[0].previous};near(base.revenueSeries[0].previous,p.revenueSeries[0].previous);});
check('Promotion Constraint requires an actual promotion',()=>{const sku={...data.getSku('mango-12'),currentInventory:100};const inv=inventoryFor(sku,forecastSku(sku,4,[]),[]);const rec=recommend(sku,inv,[],[]);output.evidence.falsePromotion=rec.map(r=>r.title);assert.ok(!rec.some(r=>r.title==='Promotion Constraint'));});
check('Supplier timing risk requires the delay to cause the breach',()=>{const sku={...data.getSku('mango-12'),currentInventory:500};const po={id:'PROBE-DELAY',skuId:sku.id,quantity:1200,orderDate:'2026-09-01',originalArrival:'2026-10-12',expectedArrival:'2026-10-19',status:'delayed',unitCost:5};const forecast=forecastSku(sku,13,[]);const delayed=inventoryFor(sku,forecast,[po]);const ontime=inventoryFor(sku,forecast,[{...po,expectedArrival:po.originalArrival,status:'confirmed'}]);const rec=recommend(sku,delayed,[],[]);output.evidence.falseDelay={originalBreach:ontime.breach,delayedBreach:delayed.breach,recommendations:rec.map(r=>r.title)};assert.equal(ontime.breach,delayed.breach);assert.ok(!rec.some(r=>r.title==='Replenishment Timing Risk'));});
check('Literal coverage rule flags insufficient lead-time cover even outside display horizon',()=>{const s=data.getSku('lime-6');const p=engine.buildPlan({...engine.defaultState(s.id),forecastHorizon:4,leadTimeWeeks:12});output.evidence.horizonRule={cover:p.selected.inventory.weeksOfCover,requiredCover:13,risk:p.selected.inventory.risk,breach:p.selected.inventory.breach,recommendations:p.selected.recommendations.map(r=>r.title)};assert.ok(p.selected.recommendations.some(r=>r.title==='High Stockout Risk'));});
check('Lead-time change is reflected in unconfirmed future purchase orders',()=>{const p=engine.buildPlan({...engine.defaultState('peach-6'),leadTimeWeeks:12});const order=p.selected.inventory.orders.find(o=>o.id==='PLAN-8-0');const effective=(Date.parse(order.expectedArrival)-Date.parse(order.orderDate))/86400000/7;output.evidence.plannedLead={stateLead:12,order,effectiveLead:effective,risk:p.selected.inventory.risk,stockout:p.selected.inventory.stockoutDate};near(effective,12);});
check('Forecast Review requires consecutive weeks, not just last three records',()=>{const s=data.getSku('lime-6');const inv=inventoryFor(s,forecastSku(s,13,[]),data.purchaseOrders);const observations=['2026-08-03','2026-08-17','2026-09-07'].map(weekStart=>({weekStart,skuId:s.id,units:800,planUnits:700,revenue:11200,discount:0}));assert.ok(!recommend(s,inv,[],observations).some(r=>r.title==='Forecast Review Required'));});
check('Zero demand has finite outputs',()=>{const s={...data.getSku('mango-12'),baseWeeklyDemand:0};const p=inventoryFor(s,forecastSku(s,13,[]),[]);output.evidence.zeroDemand={cover:p.weeksOfCover,risk:p.risk,breach:p.breach,stockout:p.stockoutDate};const walk=v=>{if(typeof v==='number')assert.ok(Number.isFinite(v));else if(v&&typeof v==='object')Object.values(v).forEach(walk);};walk(p);});
check('Reset restores every state input atomically',()=>{const state={...engine.defaultState('berry-6'),forecastHorizon:26,scenarioMode:'upside',demandUpliftPct:50,adSpendChangePct:50,promotionEnabled:true,promotionDiscountPct:40,leadTimeWeeks:12,incomingInventory:999,purchaseQuantity:9000};assert.deepEqual(engine.planningReducer(state,{type:'reset'}),engine.defaultState());});
check('Numeric ranges and non-finite sanitization',()=>{const p=engine.sanitizeState({...engine.defaultState(),selectedSkuId:'missing',forecastHorizon:99,scenarioMode:'bad',demandUpliftPct:51,adSpendChangePct:-21,promotionDiscountPct:41,leadTimeWeeks:99,incomingInventory:-10,purchaseQuantity:1.6});assert.deepEqual(p,{...engine.defaultState(),demandUpliftPct:50,adSpendChangePct:-20,promotionDiscountPct:40,leadTimeWeeks:12,incomingInventory:0,purchaseQuantity:2});for(const value of [NaN,Infinity,-Infinity])assert.equal(engine.sanitizeState({...engine.defaultState(),demandUpliftPct:value}).demandUpliftPct,0);});
check('Human judgment override is backed by confirmed BFCM context',()=>assert.ok(base.rows.find(r=>r.sku.id==='winter-kit').recommendations.some(r=>r.title==='Business context changes the decision')));
check('Canonical history is seeded and repeatable',()=>assert.deepEqual(generateHistory(data.skus),data.history));
output.evidence.history={rows:data.history.length,start:data.history[0].weekStart,end:data.history[103].weekStart,activeSkuCount:data.skus.filter(s=>s.active).length,detailedCount:data.detailedSkus.length,postLaunchZeroDemand:data.history.filter(h=>h.units===0&&h.skuId!=='peach-6').length};
check('Zero comparable sales does not yield infinite growth',()=>{const saved=data.history.map(h=>h.revenue);try{data.history.forEach(h=>{h.revenue=0;});const p=engine.buildPlan(engine.defaultState());output.evidence.zeroComparable={previous30:p.previous30,growth:String(p.revenueGrowthPct)};assert.ok(Number.isFinite(p.revenueGrowthPct));}finally{data.history.forEach((h,i)=>{h.revenue=saved[i];});}});
check('Selected SKU validation rejects inactive products',()=>{const s=data.getSku('berry-6'),saved=s.active;try{s.active=false;const state=engine.sanitizeState({...engine.defaultState(),selectedSkuId:s.id});output.evidence.inactiveSelection={active:s.active,selected:state.selectedSkuId};assert.notEqual(state.selectedSkuId,s.id);}finally{s.active=saved;}});
output.summary={pass:output.tests.filter(t=>t.status==='pass').length,fail:output.tests.filter(t=>t.status==='fail').length};
fs.writeFileSync('audit-evidence/engine-probes.json',JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output,null,2));
